services:
  pytest:
    image: gitlab.hamrah.in:5555/zarinpal_v4/qa/quality-gate:latest
    container_name: pytest
    shm_size: '2g'
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    stdin_open: true
    tty: true
