FROM node:lts-alpine AS builder
RUN apk add python3 make gcc g++
RUN npm install -g nx pnpm@10.8.1

WORKDIR /app/
ARG BUILD_VERSION
ENV BUILD_VERSION=$BUILD_VERSION
ENV NODE_OPTIONS=--max_old_space_size=8192
COPY . .
RUN pnpm i
WORKDIR /app/apps/docs/
RUN npx storybook build -o out
FROM nginx:stable-alpine AS docs
COPY --from=builder /app/apps/docs/out /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf
